possible fix for missing glyph exception
issue when glyph is missing:

Traceback (most recent call last):
  File "adafruit_display_text/__init__.py", line 57, in wrap_text_to_pixels
  File "adafruit_display_text/__init__.py", line 48, in measure
  File "adafruit_display_text/__init__.py", line 48, in <genexpr>
AttributeError: 'NoneType' object has no attribute 'shift_x'